### ISSUE TITLE
Arrays support: char[2] treated as dchar value

### ISSUE THREAD

**Issue by denizzzka** [denizzzka/dpq2#131]
This check fails:
```D
    unittest
    {
        char[2] arr;

        auto v = arr.toValue();
        assert(v.oidType == OidType.TextArray);
        assert(!v.isNull);

        auto varr = v.asArray;
        assert(varr.length == 2);
    }
```

**Comment by schveiguy** [comment]
I'm working on adding a fix for this, because dpq2 also does not work for non-immutable strings (e.g. `const(char)[]` and `char[]`).

Is there a reason that you think the OidType should be TextArray? Isn't that an array of strings?

**Comment by schveiguy** [comment]
Looking at the docs, I think the correct postgres type for this is probably `char(2)`, right? I was going to simply make it `Text`, as that fits in already with all the existing code.

**Comment by denizzzka** [comment]
> Is there a reason that you think the OidType should be TextArray? Isn't that an array of strings?

TextArray is array of strings in PG terms.
As I remember, TextArray here used because in 2018 I wanted to treat char[2] as two PG text arrays both of length == 1 because is no symbol/character type in Postgres.

> Looking at the docs, I think the correct postgres type for this is probably char(2), right? I was going to simply make it Text, as that fits in already with all the existing code.

I avoided char and varchar everywhere. Maybe we should start using them?
