### ISSUE TITLE
Use on windows

### ISSUE THREAD

**Issue by ParchmentWolf** [denizzzka/dpq2#155]
Getting libpq.lib to cooperate on windows with Dlang was a nightmare... basically no documentation to fix the problems and I had to get some assistance from the D community on discord to solve the problem.

Any chance I could convince you to update your readme with some sort of note about getting it to run on windows? (I dont know if the usage was simpler back in postgres-v10 which had some larger differences... every version since has been a bit messy and generally follows my setup -> It only works for windows-x64 since then)

"Rename libpq.lib to pq.lib" inside C:/Program Files/PostgreSQL/<VERSION>/lib

Include the following to the bottom of the dub file for windows to pull deps and use libpq

```
"libs": [ "pq" ],
"lflags-windows": [ "-LIBPATH:C:/Program Files/PostgreSQL/<VERSION>/lib/" ],
"copyFiles-windows": [
	"C:/Program Files/PostgreSQL/<VERSION>/lib/libpq.dll",
        "C:/Program Files/PostgreSQL/<VERSION>/bin/libintl-9.dll",
        "C:/Program Files/PostgreSQL/<VERSION>/bin/libssl-1_1-x64.dll",
        "C:/Program Files/PostgreSQL/<VERSION>/bin/libcrypto-1_1-x64.dll"
]
```
(Obviously replace <VERSION> with the version of pg being used...)

In the case of the dynamic stuff... the dlls still are needed but the .lib part can be skipped i guess..

I know this would help anyone else trying to use your dub binding greatly :)

**Comment by denizzzka** [comment]
(After night with thinking about this issue)

Are you sure, it is really need to change something in build process?
For example, if you build some Postgres client why is need to force you to have DLLs in `C:/Program Files/PostgreSQL/lib` before build?

> "Rename libpq.lib to pq.lib" inside C:/Program Files/PostgreSQL//lib

lib* prefix is used on *nix systems and linker adds "lib" to any library name automatically. This is why `"libs": [ "pq" ]` is used in dub.json

Why Postgres build process for Windows resulting library also uses "lib" prefix?

**Comment by denizzzka** [comment]
@SpiceyWolf I found error with DLL loading! (commit 3d39bab1697859d43a9bd6cdf21f31cb1a957ad6)

Now it is possible to point external libpq.dll to use with dpq2. Please try to use current ~master and add these lines to your dub.sdl:
```
subConfiguration "dpq2" "dynamic"
copyFiles "postgresql-14.0-1-official-libs/libpq.dll" platform="windows-x86_64"
```
(where is `postgresql-14.0-1-official-libs/` is dir in your package)

Official binaries can be found here: https://www.postgresql.org/download/windows/ (click "download a zip archive" link)
