### ISSUE TITLE
High GC usage when accessing columns by name

### ISSUE THREAD

**Issue by tchaloupka** [denizzzka/dpq2#161]
If you use something like
```D
row["foo"].as!int
```
to get the column value it uses libpq interface `PQfnumber` to determine the index of the column and for that it uses `toStringz` that allocates the zero terminated string with GC.
Now if you read some complex structure from the DB for thousands of rows it uses a GC a lot for a short lived small strings.

We've fixed it by the workaround below, but haven't made the PR as there could be more (and better) ways to fix it. This just uses already determined indexes stored in AA in the `Answer`.

```
diff --git a/src/dpq2/result.d b/src/dpq2/result.d
index 1a3d3cd..03c43e1 100644
--- a/src/dpq2/result.d
+++ b/src/dpq2/result.d
@@ -106,6 +106,8 @@ immutable class Result
 /// Contains result of query with valid data answer
 immutable class Answer : Result
 {
+    private size_t[string] columnNumCache = null;
+
     package this(immutable ResultContainer r)
     {
         super(r);
@@ -188,7 +190,11 @@ immutable class Answer : Result
     /// Returns column number by field name
     size_t columnNum( string columnName )
     {
-        size_t n = PQfnumber(result, toStringz(columnName));
+        size_t[string]* pColumnNumCache = cast(size_t[string]*)&columnNumCache;
+        size_t* pn = columnName in (*pColumnNumCache);
+        size_t n;
+        if (pn) { n = *pn; }
+        else { n = PQfnumber(result, toStringz(columnName)); (*pColumnNumCache)[columnName] = n; }
 
         if( n == -1 )
             throw new AnswerException(ExceptionType.COLUMN_NOT_FOUND,

```

**Comment by denizzzka** [comment]
`Answer` is immutable class and, as I remember, it will not be able to maintain mutable cache

I think, it is better to wrap `Answer` into something (like rangify does) on caller application side.

**Comment by tchaloupka** [comment]
Yes, immutability is casted away. It's hacky but was an easiest way to fix that -> but is the reason why we haven't made the PR with this ;-)
It might be right in the `rangify` but it would need to wrap rows with opIndex. But it would change the interface of the range.
Not sure how to fix this the best way.

It might be possible to make index AA while building answer itself too.

**Comment by radcapricorn** [comment]
@tchaloupka 
1) There's an `update` function for AAs designed specifically to avoid double lookup
2) This looks like a nuclear solution. A trivial small string implementation should suffice (i.e. a small buffer to copy name + null terminator into, malloc/free if length too large).
3) A template version of `columnNum` that would take name as template argument would avoid the whole issue altogether, since string literals are null-terminated

**Comment by denizzzka** [comment]
> It might be possible to make index AA while building answer itself too

But `libpq` already implements this AA and API for access to it: `PQfnumber()` :-)

> It might be right in the rangify

Anyone can implement its own `rangify` or pass its own implementation of `Answer` to `rangify`

**Comment by tchaloupka** [comment]
>     1. There's an `update` function for AAs designed specifically to avoid double lookup. And `require` as well, which creates an element only if it doesn't exist.

Oh, thanks, I'm so used to that idiom, never noticed those - seems to be introduced in 2.082.0, that's pretty long time ago :)

>     2. This looks like a nuclear solution. A trivial small string implementation should suffice (i.e. a small buffer to copy name + null terminator into, malloc/free if length too large).

No doubt about being nuclear :) Yes in druntime there is `tempCString`, something like that would be most trivial change that won't intercept in what is already in. Not sure what would be more performant (AA lookup or nogc tostringz). But definitely still better than GC based `toStringz`.

>     3. A template version of `columnNum` that would take name as template argument would avoid the whole issue altogether, since string literals are null-terminated

`columnNum` is called from rows `opIndex` so no templated value there.

**Comment by tchaloupka** [comment]
@denizzzka  would you be ok with a simplified version of [tempCString](https://github.com/dlang/phobos/blob/cd7389266e10f10548fbc59fb6ce365103ef2b85/std/internal/cstring.d#L77) to be used instead of `toStringz`?

I'd prefer this personally as it doesn't leave user that is not aware of the GC problematic interface to handle it by himself to be shot in the foot like we were.

**Comment by schveiguy** [comment]
This shouldn't be too hard:

```d
size_t n = (const char*v) @trusted {
    auto tmpstr = columnName.tempCString; // freed at the end of the scope, also uses SSO
    return PQfnumber(result, tmpstr);
} ();
```

**Comment by denizzzka** [comment]
> @denizzzka would you be ok with a simplified version of tempCString to be used instead of toStringz?

I just heard about it for the first time. It seems this is what is need.

The main thing is not to spoil anything - CI is broken already  :-)

**Comment by tchaloupka** [comment]
Ok, PR is alive - thanks @schveiguy

**Comment by schveiguy** [comment]
> CI is broken already

I recommend switching to Github actions. So much faster, and no stupid "credits" to deal with. mysql-native's CI now runs in about 3 minutes, used to take like 15 or 20.

**Comment by denizzzka** [comment]
> I recommend switching to Github actions

It takes time (that I do not currently have) to learn the nuances

**Comment by denizzzka** [comment]
@schveiguy but we could also wrote:
```d
size_t n = PQfnumber(result, columnName.tempCString); // just subst toStringz by tempCString
```
...to avoid additional unnamed function call?

**Comment by schveiguy** [comment]
Explanation of why I implemented that way:

1. I don’t know the safe requirements of dpq2. toStringz is safe, tempCString is not. So I wanted to wrap in a trusted call.
2. tempCString converts to a char * that is pointing at stack data. It’s not a good idea to pass it directly to a C function using a temporary. So you need to store the variable first.
3. In order for a trusted function to be proper it should explicitly accept its parameters. Otherwise it gets access to the whole context. In a future version of d this might be enforced, so passing the parameters to the lambda is mostly future proof

if dpq2 has no safety requirements you can eliminate the use of a lambda. But keep the separate variable storage of the temp c string.

**Comment by denizzzka** [comment]
Thank you for explain!
