### ISSUE TITLE
Windows and dynamic load

### ISSUE THREAD

**Issue by denizzzka** [denizzzka/dpq2#165]
If `libpq.dll` will not be dynamically loaded properly for some reason (lack of DLL or 32/64 bit versions mismatch, for example) application will be notified by exception error message. But subsequent calls to `dpq2` methods will cause crash.

What if we totally drop of support of dynamic DLL loading from static ctor to avoid cases like described above?

**Comment by denizzzka** [comment]
Another idea: if dynamic loader is used Connection must be created by loader method. Thus, if DLL isn't loaded it will be not possible to try to connect (or do some another calls) to `libpq.dll`

**Comment by denizzzka** [comment]
@SpiceyWolf hi! I think this this issue is important for your usecases

**Comment by SpiceyWolf** [comment]
only issue im familiar with libpq having on windows is dub trying to strip the "lib" string from the prefix making it refuse to find it... any versions people are reasonably going to use anymore require 64bit only now if im not mistaken as well.

the other issue where I proposed a snippet for readme that people could put in their projects dub file was moreso for ease of use, as having to carry around duplicate copies of the lib with project seems unnecessary when you still have to install the suite (and said libraries) in a static location anyway.

**Comment by denizzzka** [comment]
> only issue im familiar with libpq having on windows is dub trying to strip the "lib" string from the prefix 

I use dynamic loading for Windows. Postgresql provides official libpq.dll what works fine with current dpq2 without renaming (and except this issue)

**Comment by denizzzka** [comment]
Proposed soution: https://github.com/denizzzka/dpq2/pull/166

**Comment by denizzzka** [comment]
fixed #166
