### ISSUE TITLE
Representation of the binary query for numeric

### ISSUE THREAD

**Issue by ilya-stromberg** [denizzzka/dpq2#17]
Хочется добавить поддержку запросов в бинарном режиме для чисел с произвольной точностью numeric.

На сколько я понял, вы этого еще не сделали потому что в Phobos нет подходящего типа данных. Я набросал простейший тип BigDecimal для десятичных чисел с произвольной точностью, есть поддержка простейших арифметических операций `+-*/`. Он доволно простой - ~150 строчек кода, фактически просто обертка над std.bigint. При необходимости могу попробовать доработать и выложить в общий доступ.

В качестве альтернативы есть еще std.decimal:
https://github.com/andersonpd/decimal
Я нашел его в списке готовых к рассмотрению модулей, правда уже после того как написал свой:
http://wiki.dlang.org/Review_Queue
Правда там указан статус "Ready for comments", так что в ближайшее время этот модуль в Phobos не включат.
Подробно этот модуль я не изучал, но, похоже, он так же реализует десятичные числа с произвольной точностью и тоже использует std.bigint в качестве основы.

Вобщем, нужно выеяснить, в каком виде передает данные PostgreSQL, как их хранит std.bigint и написать конвертор. Если есть идеи с чего начать, хотя бы касательно вопросов базы данных, буду благодарен за помошь.

**Comment by denizzzka** [comment]
разбор numeric в D переехал:
https://github.com/DSoftOut/pgator-backend/blob/master/source/pgator/db/pq/types/numeric.d

**Comment by denizzzka** [comment]
bigfloat неплох - думаю использовать его:
https://github.com/andersonpd/decimal/blob/master/decimal/bigfloat.d

**Comment by denizzzka** [comment]
бамп! опять назрело. Что сейчас актуально в области больших floating-point чисел?

**Comment by denizzzka** [comment]
сделал пока что текстом, если будет актуально создавайте новый тикет
