### ISSUE TITLE
Answer rowCount property?

### ISSUE THREAD

**Issue by ddcovery** [denizzzka/dpq2#181]
Answer doesn't include information to know the number of affected rows (row_count)

*Why it is necessary?*

Because it is the only way to know how many rows have been affected by an `update`, `delete` or `insert`query.

**Comment by denizzzka** [comment]
https://github.com/denizzzka/dpq2/blob/474ef7d6479dad971d60c199d0e215cb4b300710/src/dpq2/result.d#L150

Yes, it's a little strange that the command returns a string instead of an integer, but this is how libpq provides this information

**Comment by ddcovery** [comment]
Thanks @denizzzka.
