### ISSUE TITLE
Support for "pipeline mode"

### ISSUE THREAD

**Issue by VPanteleev-S7** [denizzzka/dpq2#196]
Documentation: https://www.postgresql.org/docs/current/libpq-pipeline-mode.html

I think it would be interesting if dpq2 supported libpq's pipeline mode (functions `PQenterPipelineMode`, `PQpipelineStatus`, etc.).

~~One thing that this would allow is doing a `SELECT 1;` periodically while a long query is running. Then we can know if the server is still alive (and still thinking), or if the connection is dead.~~

Thanks!

**Comment by denizzzka** [comment]
We found out behind the scene that this is not needed now

But everything is almost ready for this. If anyone needs it, write here or just implement it: it looks only two calls needed to be implemented

**Comment by denizzzka** [comment]
https://github.com/denizzzka/vibe.d.db.postgresql/blob/master/example_pipelining/pipelining.d
