### ISSUE TITLE
Support vibe.d?

### ISSUE THREAD

**Issue by DarkRiDDeR** [denizzzka/dpq2#28]
Планируется ли внедрение поддержки vibe.d? Хотелось бы видеть ))
Для примера можно посмотреть http://vibed.org/blog/posts/writing-native-db-drivers 
а также библиотеки
https://github.com/pszturmaj/ddb
https://github.com/mysql-d/mysql-native

**Comment by denizzzka** [comment]
Подразумевается, переписать драйвер не используя стандартную библиотеку, а используя vibe'd сокеты?

Какие это даёт преимущества?

**Comment by denizzzka** [comment]
Прочитал. Кратко: если это действительно надо то нужно просто написать обёртку поверх.

Дело в том, что libpq (клиентская библиотека postgres) не умеет события в том виде, в котором хочет vibe.d. То есть, нужно сделать процесс, отслеживающий события от libpq и уже им генерировать эти события.

**Comment by DarkRiDDeR** [comment]
> Дело в том, что libpq (клиентская библиотека postgres) не умеет события в том виде, в котором хочет vibe.d. 

Да. Это основная проблема

**Comment by denizzzka** [comment]
Ну всё просто достаточно тогда выглядит:

* проверяем библиотеку libpq на мультитредность
* соединяемся в RDBMS
* принимаем запросы
* ждём ответов асинхронно (коллбэков для сокетов, вроде, нет - значит форкаем контрольный процесс и в нём ждём когда в сокет что-то придёт)
* генерируем событие для vibe.d

**Comment by DarkRiDDeR** [comment]
Будешь браться?

**Comment by NCrashed** [comment]
> значит форкаем контрольный процесс

Надеюсь, что имелось ввиду "создаем новый поток", так как `fork` в D приводит к непредсказуемым результатам.

**Comment by denizzzka** [comment]
Я vibe.d не пользовался.

**Comment by denizzzka** [comment]
> Надеюсь, что имелось ввиду "создаем новый поток", так как fork в D приводит к непредсказуемым результатам.

core.thread имелся ввиду

**Comment by DarkRiDDeR** [comment]
> Я vibe.d не пользовался.

Для этой задачи его почти и не надо использовать, т.к. лишь затрагиваются функции сокетов

**Comment by denizzzka** [comment]
Ну опенсорс же! Правила такие: кому надо - тот и делает. Набросай, а там поглядим. Задача не выглядит сложной.

Важно тестами покрыть этот момент прихода (и не прихода) данных в сокет, чтобы баг не посадить - это место кажется ответственным.

**Comment by denizzzka** [comment]
@NCrashed кстати, в pgator-backend есть же подобный код? он же там ждёт асинхронно?

**Comment by DarkRiDDeR** [comment]
> Ну опенсорс же! Правила такие: кому надо - тот и делает. Набросай, а там поглядим. Задача не выглядит сложной.

Понятно. Хорошо, тогда

**Comment by denizzzka** [comment]
вопрос как-то заглох

**Comment by denizzzka** [comment]
https://github.com/denizzzka/vibe.d.db.postgresql
