### ISSUE TITLE
Requests and questions:

### ISSUE THREAD

**Issue by denizzzka** [denizzzka/dpq2#45]
Please feel free to request something!

**Comment by AndrewSChapman** [comment]
Hi there.  In the Answer class you have:

    /// Returns column number by field name
    size_t columnNum( string columnName )
    {    
        size_t n = PQfnumber(result, toStringz(columnName));

        if( n == -1 )
            throw new AnswerException(ExceptionType.COLUMN_NOT_FOUND,
                    "Column '"~columnName~"' is not found", __FILE__, __LINE__);

        return n;
    }

Might it be possible to add another method "columnExists", e.g.

    /// Returns true if a column exists, false if not.
    bool columnExists( string columnName )
    {    
        size_t n = PQfnumber(result, toStringz(columnName));

        return ( n > -1 );
    }

**Comment by denizzzka** [comment]
PRs are welcomed! Ideally with testing coverage.

But I insist on comparing n == -1 here because "-1 is returned if the given name does not match any column." (Postgres manual)

**Comment by AndrewSChapman** [comment]
Thanks!  

OK so I'm implemented the change and uploaded it to GITHub, however please forgive my ignorance (I'm new to the D ecosystem), but I have no idea how to test it or run the integration test.  

I'm on Windows and if I try and run Dub it complains that the target is sourceLibrary, not executable.  If i try to do dmd on the integration_tests.d file then it says:
Error: module dpq2 is in file 'dpq2.d' which cannot be read

How do I test a sourceLibrary project and run the integration_tests.d?

**Comment by denizzzka** [comment]
> but I have no idea how to test it or run the integration test.

Simpliest way is just make a PR, and CI system will try to build and run it

> I'm on Windows

dpq2 works well in WIndows?

> If i try to do dmd on the integration_tests.d file then it says:
> Error: module dpq2 is in file 'dpq2.d' which cannot be read

> How do I test a sourceLibrary project and run the integration_tests.d?

.test.sh contains CI tests commands for Linux. You can run:
```
dub run dpq2:integration_tests --build=unittest-cov -- --conninfo="<your connection string here>"
```
(It would be very cool to configure CI for Windows. But I am not know any free service for it.)

**Comment by AndrewSChapman** [comment]
Awesome, thanks!  Yes it's running well on Windows so far :-)  I'm building an ORM of sorts using pq2 and vibe.d (hence the need for a columnExists method, because I'm using compile-time reflection to automatically populate structs based on the Answer class from dbq2.  Thanks for your work on this btw.

**Comment by AndrewSChapman** [comment]
OK, so the integration tests seems to fail on Windows in connection.d:

    Socket socket()
    {
        version(Posix)
        {
            import core.sys.posix.unistd: dup;

            socket_t s = cast(socket_t) dup(cast(socket_t) posixSocket);
            return new Socket(s, AddressFamily.UNSPEC);
        }
        else version(Windows)
        {
            assert(false, "FIXME: implement socket duplication");
        }
    }

Interestingly, dbq2 works fine in my project - any thoughts on why this might be different when running the integration tests?

**Comment by denizzzka** [comment]
> Thanks for your work on this btw.

:3

> Interestingly, dbq2 works fine in my project - any thoughts on why this might be different when running the integration tests?

Your code isn't uses socket() and this function isn't compiles into binary. This is normal behaviour of compiler.

**Comment by denizzzka** [comment]
> I'm building an ORM of sorts using dpq2 and vibe.d

Can I see your coupling of vibed and dpq2?

**Comment by AndrewSChapman** [comment]
Yup you sure can.  I'll try and get in into a reasonable state this weekend and let you know once available.  Cheers.

**Comment by denizzzka** [comment]
closing for code.dlang.org scoring increase :-)
