### ISSUE TITLE
Error during attampt to connect to PostgreSQL

### ISSUE THREAD

**Issue by bubnenkoff** [denizzzka/dpq2#48]
I am trying to connect to PG, but getting error: 

`Error: function core.sys.windows.winsock2.socket (int af, int type, int protocol) is not callable using argument types ()`

Code is next:
```
Connection conn = new Connection("dbname=" ~ config.dbname);
auto answer = conn.exec(`SELECT guid, name, "FL", id FROM public."USERS";`);
```

**Comment by denizzzka** [comment]
Hmm. Can you provide file name where this error has occurred?
(I never tried to compile dpq2 for Windows, but there is no reason why it should not be compile.)

**Comment by bubnenkoff** [comment]
```
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\dpq2-0.6.12\dpq2\src\dpq2\quer
y.d(139,29): Error: function core.sys.windows.winsock2.socket (int af, int type,
 int protocol) is not callable using argument types ()
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\dpq2-0.6.12\dpq2\src\dpq2\conn
ection.d(137,40): Error: template object.dup cannot deduce function from argumen
t types !()(socket_t), candidates are:

```

**Comment by denizzzka** [comment]
Please provide also compiler version

**Comment by denizzzka** [comment]
...and please try new ~master version

**Comment by bubnenkoff** [comment]
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\dpq2-0.6.12\dpq2\src\dpq2\conn
ection.d(137,40): Error: template object.dup cannot deduce function from argument types !()(socket_t), candidates are:
C:\D\dmd2\windows\bin\..\..\src\druntime\import\object.d(1903,6):        object.
dup(T : V[K], K, V)(T aa)
C:\D\dmd2\windows\bin\..\..\src\druntime\import\object.d(1939,6):        object.
dup(T : V[K], K, V)(T* aa)
C:\D\dmd2\windows\bin\..\..\src\druntime\import\object.d(3277,16):        object
.dup(T)(T[] a) if (!is(const(T) : T))
C:\D\dmd2\windows\bin\..\..\src\druntime\import\object.d(3293,15):        object
.dup(T)(const(T)[] a) if (is(const(T) : T))
C:\D\dmd2\windows\bin\..\..\src\druntime\import\object.d(3304,15):        object
.dup(T : void)(const(T)[] a)
dmd failed with exit code 1.

**Comment by denizzzka** [comment]
please provide your comiler version
(пожалуйста, напишите версию вашего компилятора)

**Comment by bubnenkoff** [comment]
D:\Project\2016\DBSync>dmd -v
DMD32 D Compiler v2.070.0

2016-04-05 15:54 GMT+03:00 Denis Feklushkin <notifications@github.com>:

**Comment by denizzzka** [comment]
Try to use dmd 2.070.2

**Comment by bubnenkoff** [comment]
I decided to try 2.071 b-2 and got a heap of errors
http://img.ctrlv.in/img/16/04/05/5703bfb81bc6a.png

2016-04-05 16:21 GMT+03:00 Denis Feklushkin <notifications@github.com>:

**Comment by bubnenkoff** [comment]
http://img.ctrlv.in/img/16/04/05/5703c0be9e73b.png

2016-04-05 16:38 GMT+03:00 Dmitry Bubnenkov <bubnenkoff@gmail.com>:

**Comment by denizzzka** [comment]
Please use latest stable dmd
In next version importing rules are slightly changed, as I know.

**Comment by denizzzka** [comment]
it is works with latest stable dmd?

**Comment by bubnenkoff** [comment]
Я чуть выше скрин скинул от версии 2.070.2. Тоже как видишь не собралось.

**Comment by denizzzka** [comment]
пробуй опять, вроде поправил

**Comment by denizzzka** [comment]
(очень странная история - одинаковые компиляторы путаются в синтаксисе или версии библиотеки под винду совсем по-другому выглядят для него)

**Comment by bubnenkoff** [comment]
http://img.ctrlv.in/img/16/04/06/5704be940d53e.png

**Comment by denizzzka** [comment]
пробуй. из последнего патча видно в чём там проблема. я пофиксить это не смогу - нету винды у меня.

**Comment by bubnenkoff** [comment]
Спасибо, Завтра тогда на работе глянуть смогу.

6 апреля 2016 г., 18:30 пользователь Denis Feklushkin <
notifications@github.com> написал:

**Comment by denizzzka** [comment]
Ок. Компиляцию под новый компилятор тоже пофиксил.

Вообще, если планируете использовать эту библиотеку рекомендую настроить continuous integration под Windows (типа как travis-ci сейчас линуксовую версию собирает) и прислать патч на эту тему. Потому что я время от времени вношу разные изменения, которые могут сломать виндовую сборку, но никто о поломке может и не узнать.

**Comment by bubnenkoff** [comment]
connection.d(147,27): Error: undefined identifier 's'

```
    Socket socket()
    {
        version(Posix)
        {
            import core.sys.posix.unistd: dup;

            socket_t s = cast(socket_t) dup(cast(socket_t) posixSocket);
        }
        else version(Windows)
        {
            assert(false, "FIXME: implement socket duplication");
        }

        return new Socket(s, AddressFamily.UNSPEC); // here
    }

```

Немного не по теме, но, но куда еще написать не знаю, а ты в ПГ
разбираешься очень хорошо. Ну так вот.
Я тут застрял вот с чем. В PG мне нужно блоб хранить. Для этого
используется поле bytea. Как я понимаю PG данные будет отдавать в виде
16-тиричной последовательности, но не простой, а с рядом дополнительных
символов (экраниерование разных последовательностей)

http://www.postgresql.org/docs/current/static/datatype-binary.html

In some contexts, the initial backslash may need to be escaped by doubling
it, in the same cases in which backslashes have to be doubled in escape
format;

Вопрос вот. Как мне данные перевести в byte [] и записать и создать на их
основе нормальный файл.

Сегодня промаялся весь день. Вот итоги:
http://stackoverflow.com/questions/36469669/how-to-load-unload-binary-blob-from-postgresql-with-d

http://forum.dlang.org/thread/oibiefnowwsnokqmpsax@forum.dlang.org

Собственно вопрос - как быть то? Как мне загрузить/выгрузить данные?



6 апреля 2016 г., 19:22 пользователь Denis Feklushkin <
notifications@github.com> написал:

**Comment by denizzzka** [comment]
> connection.d(147,27): Error: undefined identifier 's'

моя ошибка, исправил вроде - пробуй

**Comment by denizzzka** [comment]
> Я тут застрял вот с чем. В PG мне нужно блоб хранить. Для этого
используется поле bytea. Как я понимаю PG данные будет отдавать в виде
16-тиричной последовательности, но не простой, а с рядом дополнительных
символов (экраниерование разных последовательностей)

Нет, он прямо чистый бинарник и отдаст.
Про слэши там написано в смысле передачи их в виде аргумента в текстовой строке запроса.

Будешь использовать dpq2 и функции типа execParams - всё будет работать безо всяких танцев с бубном

**Comment by bubnenkoff** [comment]
А то что мне про функцию
byte[] byteaToBytes(string s)
написали на SO это в ту степь?

7 апреля 2016 г., 17:25 пользователь Denis Feklushkin <
notifications@github.com> написал:

**Comment by bubnenkoff** [comment]
Не мог бы механизм объяснить как 6-тиричные значения в файл переводятся?
Там просто или есть какие-то нюансы?

7 апреля 2016 г., 17:28 пользователь Dmitry Bubnenkov <bubnenkoff@gmail.com>
написал:

**Comment by denizzzka** [comment]
(добавил поддержку аргументов запроса типа ubyte[])

> А то что мне про функцию
> byte[] byteaToBytes(string s)
> написали на SO это в ту степь?

Видимо, в DDBC как-то по-другому сделано.

> Не мог бы механизм объяснить как 6-тиричные значения в файл переводятся?
> Там просто или есть какие-то нюансы?

16-ричные, hex? Если да то на самом деле они восьмеричные, то есть это просто байты (октеты).
Тебя сбил с толку различный возможный способ их ввода в постгрес: их можно передавать в восьмеричном, а можно передавать в 16-ричном виде в строке SQL-запроса.

**Comment by bubnenkoff** [comment]
Ну вот в доке написано: "The "hex" format encodes binary data as 2 hexadecimal digits per byte".

Потом пишут: "The entire string is preceded by the sequence \x (to distinguish it from the escape format). In some contexts, the initial backslash"

Тоесть они тут именно про передачу пишут, а не про хранение?

И опять когда они говорят про ввод они и про вывод говорят, тоесть складывается чувство, что оно и выводится в таком формате.

Не мог бы как-то вопрос этот расписать по простому "для дурака", просто надо детально все понять, а то если не проясню для себя что-то, то со временем опять будут дурацкие вопросы.

Вот данные хранятся в бинарном формате. Так? Никаких заголовков к ним не дописывается. Вот тупо 1к1 так? Получается заливаться и выгружаться могут в другом формате? Объясни плиз как он устроен? И вот допустим мы по http в базу данные передаем. Драйвер их как бинарные данные передает или в hex формате?

**Comment by denizzzka** [comment]
> Ну вот в доке написано: "The "hex" format encodes binary data as 2 hexadecimal digits per byte".
> 
> Потом пишут: "The entire string is preceded by the sequence \x (to distinguish it from the escape format). In some contexts, the initial backslash"
> 
> Тоесть они тут именно про передачу пишут, а не про хранение?

Да. Речь о таком синтаксисе: SELECT E'\\xFF'::bytea;

> И опять когда они говорят про ввод они и про вывод говорят, тоесть складывается чувство, что оно и выводится в таком формате.

Подозреваю, про вывод они имеют ввиду текстовый вывод, а не бинарный. В постгресе есть два способа закинуть аргументы и вернуть результат запроса: текстовый способ (asciiz-строки) и бинарный способ. Видимо, если попросить вернуть SELECT E'\\xFF'::bytea в виде текстового ответа то придёт какой-то текстовый заэскейпленный результат.
Чтобы этого избежать в аргументе для запроса проси постгрес вернуть бинарный ответ.

> Вот данные хранятся в бинарном формате. Так? Никаких заголовков к ним не дописывается. Вот тупо 1к1 так?

Вероятнее всего (я так глубоко не копал, но, вроде, бинарные ответы совпадают с внутренним представлением)

> Получается заливаться и выгружаться могут в другом формате?

Аргументы (каждый отдельно) и ответ (целиком) могут быть закодированы в текстовом и бинарном формате. Проще всего всегда использовать бинарный ответ и не париться раскодировкой на твоей стороне.

> Объясни плиз как он устроен? И вот допустим мы по http в базу данные передаем.

Нету такого интерфейса у постгреса

> Драйвер их как бинарные данные передает или в hex формате?

**Comment by bubnenkoff** [comment]
Ок пасибо)
Погоди, вот как мне теперь с помощью твоего кода получить в переменную бинарное представление? Не мог бы пример показать?

**Comment by denizzzka** [comment]
Так а компилируется уже?

**Comment by denizzzka** [comment]
> Погоди, вот как мне теперь с помощью твоего кода получить в переменную бинарное представление? Не мог бы пример показать?

Когда cnhernehe QueryParams передаёшь то в ней можно задать тип ожидаемого ответа (resultFormat). По умолчанию он уже бинарный, т.е. делать ничего не нужно.

**Comment by bubnenkoff** [comment]
Да, сейчас компилится, но вылетает. В каком месте логин-пароль к БД указывать -- в примерах что-то не вижу.

```
import std.stdio;
import dpq2;

void main()
{
	Connection conn = new Connection("dbname=test");
	auto answer = conn.exec(`SELECT customer_name FROM public."customers";`);
}
```
Вывод:

dpq2.connection.ConnectionException@..\..\..\AppData\Roaming\dub\packages\dpq2-
.6.14\dpq2\src\dpq2\connection.d(50): could not connect to server: Connection r
fused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

**Comment by denizzzka** [comment]
> Да, сейчас компилится, но вылетает.

Выглядит нормально, вроде

> В каком месте логин-пароль к БД указывать -- в примерах что-то не вижу.

Соединение только через conninfo string:
http://www.postgresql.org/docs/9.5/static/libpq-connect.html раздел 31.1.1. Connection Strings

**Comment by denizzzka** [comment]
Раз собирается то закрываю

**Comment by denizzzka** [comment]
> auto answer = conn.exec(`SELECT customer_name FROM public."customers";`);

точка с запятой в конце не имеет смысла здесь

**Comment by bubnenkoff** [comment]
А не мог бы пример строки подключения привести, а то я Си вообще не знаю. И что то сел делать снова и застрял.

**Comment by bubnenkoff** [comment]
Я попробовал сделать вот так:

```
    Connection conn = new Connection;
    conn.connString = "host=localhost port=5432 dbname=test user=postgres password=123";
    conn.connect();
```
Но вот какая ошибка вылезла:
source\app.d(32,23): Error: None of the overloads of '__ctor' are callable using argument types (), candidates are:
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\dpq2-0.6.15\dpq2\src\dpq2\connection.d(43,5):        dpq2.connection.Connection.this(string connString)
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\dpq2-0.6.15\dpq2\src\dpq2\connection.d(54,5):        dpq2.connection.Connection.this(ConnectionStart, string connString)
source\app.d(33,9): Error: no property 'connString' for type 'dpq2.connection.Connection'
source\app.d(34,9): Error: no property 'connect' for type 'dpq2.connection.Connection'

**Comment by denizzzka** [comment]
Строка подключения парсится в рантайме библиотекой libpq.
Пример подключения прямо в README написан же.

**Comment by bubnenkoff** [comment]
Не мог бы глянуть что там можно поправить? А то я уже все доступные драйвера перепробовал. Ни один как надо не заработал. Жесть блин какая-то.

**Comment by denizzzka** [comment]
> Не мог бы глянуть что там можно поправить?

В первой же строке ошибка - мало параметров в new Connection() - должна быть как раз строка подключения там задана
И компилятор на неё и на другие ошибки вполне прямо указывает.

**Comment by bubnenkoff** [comment]
```
void main()
{	
	byte [] x; 
	string c = "host=localhost port=5432 dbname=test01 user=postgres password=123";
	Connection conn = new Connection(c);
	
	QueryParams p;
	p.sqlCommand = `SELECT userblob FROM "USERS"`;
	auto r = conn.execParams(p);
	
	x = r[0].as!PGbytea;

}
```
Ругается:
 Error: no overload matches for as(T)(in Value v) if (is(T == string))

**Comment by denizzzka** [comment]
Правильно ругается: в r лежит весь ответ целиком, ты берёшь первую его строку и пытаешься всю строку засунуть в блоб
Нужно выбрать столбец:
x = r[0][0].as!PGbytea;

**Comment by denizzzka** [comment]
@bubnenkoff ну как, работает оно под виндой?

**Comment by bubnenkoff** [comment]
Позже гляну еще раз. У меня Firebird так и не запахал, пришлось только из
за него все на шарп переписывать.

пятница, 15 апреля 2016 г. пользователь Denis Feklushkin написал:

**Comment by denizzzka** [comment]
> Firebird

в D sqlite3 вполне юзабелен если локальная база нужна
https://github.com/denizzzka/dianna2 тут её использую

**Comment by bubnenkoff** [comment]
Мне firebird нужна и бинарные блобы(( с бинарными блобами драйвер адама
которые через odbc не работает

пятница, 15 апреля 2016 г. пользователь Denis Feklushkin написал:

**Comment by denizzzka** [comment]
> Мне firebird нужна 

Не совсем понял тогда при чём тут биндинг для постгреса )

**Comment by bubnenkoff** [comment]
Не я к тому что пришлось эксперименты с ПГ прекратить)

пятница, 15 апреля 2016 г. пользователь Denis Feklushkin написал:
