### ISSUE TITLE
Cyclic dependency between module dpq2.oids and dpq2

### ISSUE THREAD

**Issue by kmq** [denizzzka/dpq2#51]
Running under dmd v2.072.0 on windows there is an error concerning module imports. Running a compiled project fails like this:

object.Error@src/rt/minfo.d(356): Cyclic dependency between module dpq2.oids and dpq2
dpq2.oids* ->
dpq2.result ->
dpq2* ->
dpq2.oids*

It seems v2.072.0 is stricter about this than previous versions.

**Comment by denizzzka** [comment]
Hi! You are working on fixing this?

~master now contains deprecated features warnings fix

**Comment by kmq** [comment]
I forked to take a look, but I am not sure how to best fix it. [The code causing the issue](https://github.com/denizzzka/dpq2/blob/master/src/dpq2/oids.d#L41) already has a FIXME, but for something probably unrelated. 

Just moving the exception class into value.d doesn't fix it though, it just changes the path of the circle somewhat. What I think is needed to make oid.d a leaf dependency. I haven't tried that though, and I am not doing anything on it further today.

**Comment by denizzzka** [comment]
> I forked to take a look, but I am not sure how to best fix it. 

Me too. Also, I do not see anything bad in circular dependencies

> The code causing the issue already has a FIXME, but for something probably unrelated.

Yes, unrelated

> Just moving the exception class into value.d doesn't fix it though,

It is would be best to move exception into separate module dpq2.exception

> it just changes the path of the circle somewhat. What I think is needed to make oid.d a leaf dependency. I haven't tried that though, and I am not doing anything on it further today.

I planning to try solve this in a few days.
