### ISSUE TITLE
Error: Range Violation

### ISSUE THREAD

**Issue by cmays90** [denizzzka/dpq2#52]
core.exception.RangeError@../.dub/packages/dpq2-0.6.19/dpq2/src/dpq2/args.d(65): Range violation

Running an insert statement, though I would imagine that this would occur in more situations with empty strings as well. This appears to be a result of changes made in https://github.com/denizzzka/dpq2/commit/8b0ec1f915f4deba8f91ded68b05c5e81888f130.

The value causing an the error is an empty string.  I have reverted to 0.6.18

**Comment by denizzzka** [comment]
Too drunk today (wedding!).

I can watch it in few days.

**Comment by denizzzka** [comment]
Please try 4604b0f01f5

**Comment by denizzzka** [comment]
Also, please post your INSERT test case here - I want to add it to integration tests

**Comment by cmays90** [comment]
Using ````null```` isn't a sane default here.

If there's an empty string, the length of the data is ````0````, so it's subbing in a ````null```` value instead of an empty string.

I would imagine it would fail to return proper results on any ````SELECT```` when trying to find rows with an empty string.  ````SELECT * FROM table WHERE field=$1```` and the param is an empty string.

Here's a sample; it's not a unittest, but it works.

    import std.stdio;
    import dpq2;


    void main()
    {

        auto conn = new Connection("dbname=postgres user=postgres");

        QueryParams p;

        p.sqlCommand = "DROP TABLE IF EXISTS nullInsertTest";
        conn.execParams(p);

        p = QueryParams.init;
        p.sqlCommand = "CREATE TEMPORARY TABLE nullInsertTest (\"field\" TEXT NOT NULL)";
        conn.execParams(p);

        p = QueryParams.init;
        p.sqlCommand = "INSERT INTO nullInsertTest VALUES ($1)";
        p.args = [toValue("")];

        auto result = conn.execParams(p);

        assert(result[0][0].as!PGtext == "");

        p = QueryParams.init;
        p.sqlCommand = "DROP TABLE nullInsertTest";
        conn.execParams(p);
    }

**Comment by denizzzka** [comment]
try it again, please

**Comment by cmays90** [comment]
Perfect!  Thanks for your help!
