### ISSUE TITLE
Documentation on converting to different types

### ISSUE THREAD

**Issue by bonniejools** [denizzzka/dpq2#53]
Hi,

I'm having some trouble understanding why a standard `exec` can't return anything except text (especially since the type appears to be stored in the OidType?

Every time I try to convert to a `boolean`, for example, I receive the following error:

    dpq2.exception.AnswerConvException@../.dub/packages/dpq2-0.6.20/dpq2/src/dpq2/conv/to_d_types.d(76): Format of the column is not binary

What is the correct way of getting a boolean? Do I need to use the `execParams` method?

**Comment by denizzzka** [comment]
Please show your code

**Comment by bonniejools** [comment]
My code is as follows. I am trying to test whether a table called 'schema_info' exists or not. I suppose you have answered my question - I just found it odd that I couldn't use `as!bool` for the result of `exec`.


```D
string query = " 
SELECT EXISTS (
   SELECT 1
   FROM   information_schema.tables 
   WHERE    table_name = 'schema_info'
);";
auto res = conn.exec(query);

if (res[0][0].as!bool) {
    writeln("It exists!");
} else {
    writeln("It doesn't exist!");
}
```
