### ISSUE TITLE
timestamp types not supported

### ISSUE THREAD

**Issue by dhasenan** [denizzzka/dpq2#61]
The README indicates that timestamps are supported, but this appears to be false. There's an old bug suggesting that support was deliberately removed because it was buggy.

**Comment by dhasenan** [comment]
This looks a little annoying to implement, honestly -- depending on the server's compilation settings, a date might be a floating point value or an integer. Eight bytes in either case.

They give a range of defined values, but it's kind of wonky. They also say the integer case is in seconds since 2000-01-01 (UTC, I'm guessing? server timezone if we're unlucky?) but that it has a resolution of 1 microsecond.

**Comment by denizzzka** [comment]
I am not know why, but as I understand, binary protocol isn't provides TZ info for "timestamp with time zone" type.

**Comment by denizzzka** [comment]
> The README indicates that timestamps are supported

Sure, but "timestamp without time zone" only.

**Comment by dhasenan** [comment]
I assumed SysTime would work. When I got an error that only Text, FixedString, Numeric or Json values worked, I assumed that time types simply weren't supported. Improving that error message would be awesome.

**Comment by denizzzka** [comment]
Can you provide code sample and error message?

**Comment by denizzzka** [comment]
Can I close this issue?

**Comment by dhasenan** [comment]
Yes, sorry, I think I got myself horribly confused.
