### ISSUE TITLE
Deprecation warnings with the latest D versions

### ISSUE THREAD

**Issue by the-Mitu** [denizzzka/dpq2#62]
`../../.dub/packages/dpq2-0.6.24/dpq2/src/dpq2/conv/time.d(74,13): Deprecation: struct core.time.FracSec is deprecated - FracSec has been deprecated in favor of just using Duration for the sake of simplicity`

It should not be hard to make the replacement, but clearer console will make it easier to debug applications. Thank you in advance! :)

**Comment by denizzzka** [comment]
I am at vacation until 15 Dec, so feel free to send PR

**Comment by denizzzka** [comment]
Can you check current LDC for this warnings?

I am planning fix this after LDC also receives this changes in Phobos

**Comment by denizzzka** [comment]
Fixed in f93fa1c8098cfb025714a8a6406e342a82f8ef13
