### ISSUE TITLE
new class ConnectionParameters

### ISSUE THREAD

**Issue by thkoch2001** [denizzzka/dpq2#7]
I'd propose a new immutable class ConnectionParameters with one method
```
   Connection connect()
```

It makes live easier, if an object does not change its state. With this proposed change there's no doubt at which point in the code a Connection is assumed to be in the connected state or not. Once a Connection exists it is also supposed to be connected.

I know that a Connection can end or break, but that's another story.

**Comment by denizzzka** [comment]
probably, const class solves this problem
